In [1]:
import numpy as np

In [2]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [3]:
np.save('my_array',arr)

In [5]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.load('my_array.npy')

array([0, 1, 2, 3, 4])

In [8]:
arr1 = np.load('my_array.npy')

In [9]:
arr2 = arr

In [10]:
np.savez('ziparray.npz', x = arr1, y = arr2)

In [11]:
archieve_arr = np.load('ziparray.npz')

In [15]:
archieve_arr['y']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arr = np.array([[1,2,3],[4,5,6]])

In [17]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
np.savetxt('mytextfile.txt', arr,delimiter = ',' )

In [22]:
np.loadtxt('mytextfile.txt', delimiter = ',')

array([[1., 2., 3.],
       [4., 5., 6.]])