In [2]:
import numpy as np
import pandas as pd

from pandas import DataFrame, Series

In [5]:
arr1 = np.arange(9).reshape(3,3)


In [7]:
arr2 = np.array([[2,3,4],[3,6,5],[7,2,5]])

In [6]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
arr2

array([[2, 3, 4],
       [3, 6, 5],
       [7, 2, 5]])

In [17]:
np.concatenate([arr1,arr2],axis = 1)

array([[0, 1, 2, 2, 3, 4],
       [3, 4, 5, 3, 6, 5],
       [6, 7, 8, 7, 2, 5]])

In [26]:
s1 = Series([2,3,4], index = ('X','U','V'))
s2 = Series([7,5], index = ('Y','Z'))

In [33]:
pd.concat([s1,s2],axis = 1)

C:\Users\Apoorv\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


0    1
U  3.0  NaN
V  4.0  NaN
X  2.0  NaN
Y  NaN  7.0
Z  NaN  5.0

In [31]:
pd.concat([s1,s2],keys = ['cat1','cat2'])

cat1  X    2
      U    3
      V    4
cat2  Y    7
      Z    5
dtype: int64

In [36]:
d1 = DataFrame(np.random.randn(4,3), columns = ('X','Y','Z'))

d2 = DataFrame(np.random.randn(3,3), columns = ('T','U','V'))

In [37]:
d1

X         Y         Z
0  1.148811  0.609150 -0.074027
1 -0.184074 -0.264784  0.848899
2 -0.961266  0.832869 -0.246557
3 -0.137201  0.043393 -1.355338

In [38]:
d2

T         U         V
0  0.242924  1.045919 -0.455093
1 -0.228370  0.288410  0.753492
2 -0.504292 -0.727098 -0.361141

In [41]:
pd.concat([d1,d2])

C:\Users\Apoorv\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


T         U         V         X         Y         Z
0       NaN       NaN       NaN  1.148811  0.609150 -0.074027
1       NaN       NaN       NaN -0.184074 -0.264784  0.848899
2       NaN       NaN       NaN -0.961266  0.832869 -0.246557
3       NaN       NaN       NaN -0.137201  0.043393 -1.355338
0  0.242924  1.045919 -0.455093       NaN       NaN       NaN
1 -0.228370  0.288410  0.753492       NaN       NaN       NaN
2 -0.504292 -0.727098 -0.361141       NaN       NaN       NaN

In [42]:
pd.concat([d1,d2],ignore_index = True)

C:\Users\Apoorv\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


T         U         V         X         Y         Z
0       NaN       NaN       NaN  1.148811  0.609150 -0.074027
1       NaN       NaN       NaN -0.184074 -0.264784  0.848899
2       NaN       NaN       NaN -0.961266  0.832869 -0.246557
3       NaN       NaN       NaN -0.137201  0.043393 -1.355338
4  0.242924  1.045919 -0.455093       NaN       NaN       NaN
5 -0.228370  0.288410  0.753492       NaN       NaN       NaN
6 -0.504292 -0.727098 -0.361141       NaN       NaN       NaN