In [1]:
import numpy as np

In [2]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [4]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [5]:
A = np.random.randn(10)
A

array([-0.6331961 , -0.80129815, -0.32768662,  0.54874446, -0.8635357 ,
       -1.01880883, -0.01760475,  0.13195842, -0.44109177, -0.45827457])

In [6]:
B = np.random.randn(10)
B

array([ 0.33662213, -1.14778356,  0.95761676,  0.48506444,  0.91012896,
       -1.0830327 , -1.48836022,  1.71990175,  0.18391685, -1.03850951])

In [7]:
# Binary Functions
np.add(A,B)

array([-0.29657397, -1.94908171,  0.62993014,  1.0338089 ,  0.04659327,
       -2.10184153, -1.50596497,  1.85186017, -0.25717492, -1.49678408])

In [8]:
np.maximum(A,B)

array([ 0.33662213, -0.80129815,  0.95761676,  0.54874446,  0.91012896,
       -1.01880883, -0.01760475,  1.71990175,  0.18391685, -0.45827457])

In [9]:
np.minimum(A,B)

array([-0.6331961 , -1.14778356, -0.32768662,  0.48506444, -0.8635357 ,
       -1.0830327 , -1.48836022,  0.13195842, -0.44109177, -1.03850951])

In [10]:
website = 'https://docs.scipy.org/doc/numpy/reference/ufuncs.html'
import webbrowser
webbrowser.open(website)

True